const { executar, buscar, listar } = require('../config/conexaoBanco');
const { textoObrigatorio } = require('../utilitarios/validadores');
const { registrarAcao } = require('../servicos/medalhasServico');
async function listarComentarios(req, res, next) { try { const pagina=Math.max(Number(req.query.page)||1,1); const limite=Math.min(Math.max(Number(req.query.limit)||20,1),50); const coluna=req.baseUrl.includes('exercicios')?'exercicio_id':'receita_id'; return res.json({ pagina, itens: await listar(`SELECT c.*, u.nome_completo, u.foto_perfil_url FROM comentarios c JOIN usuarios u ON u.id=c.usuario_id WHERE c.${coluna}=? ORDER BY c.data_criacao DESC LIMIT ? OFFSET ?`, [req.params.id,limite,(pagina-1)*limite]) }); } catch (e) { return next(e); } }
async function criarComentario(req, res, next) { try { if (!textoObrigatorio(req.body.conteudo)) return res.status(422).json({ erro: 'O comentário não pode estar vazio.' }); const receita = await buscar('SELECT id FROM receitas WHERE id=? AND ativo=1', [req.params.id]); if (!receita) return res.status(404).json({ erro: 'Receita não encontrada.' }); const r = await executar('INSERT INTO comentarios (usuario_id, receita_id, conteudo, foto_url) VALUES (?, ?, ?, ?)', [req.usuario.sub, receita.id, req.body.conteudo.trim(), req.body.foto_url || null]); await registrarAcao(req.usuario.sub, 'comentario', r.id, 5); return res.status(201).json(await buscar('SELECT * FROM comentarios WHERE id=?', [r.id])); } catch (e) { return next(e); } }
async function criarComentarioExercicio(req, res, next) { try { if (!textoObrigatorio(req.body.conteudo)) return res.status(422).json({ erro: 'O comentário não pode estar vazio.' }); const exercicio = await buscar('SELECT id FROM exercicios WHERE id=? AND ativo=1', [req.params.id]); if (!exercicio) return res.status(404).json({ erro: 'Exercício não encontrado.' }); const r = await executar('INSERT INTO comentarios (usuario_id, exercicio_id, conteudo, foto_url) VALUES (?, ?, ?, ?)', [req.usuario.sub, exercicio.id, req.body.conteudo.trim(), req.body.foto_url || null]); await registrarAcao(req.usuario.sub, 'comentario', r.id, 5); return res.status(201).json(await buscar('SELECT * FROM comentarios WHERE id=?', [r.id])); } catch (e) { return next(e); } }
async function curtirComentario(req, res, next) { try { const comentario=await buscar('SELECT id FROM comentarios WHERE id=?',[req.params.id]); if(!comentario)return res.status(404).json({erro:'Comentário não encontrado.'}); await executar('UPDATE comentarios SET curtidas=curtidas+1 WHERE id=?',[comentario.id]); return res.json({sucesso:true}); } catch(e){return next(e);} }
async function removerComentario(req, res, next) { try { const comentario = await buscar('SELECT * FROM comentarios WHERE id=?', [req.params.id]); if (!comentario) return res.status(404).json({ erro: 'Comentário não encontrado.' }); if (comentario.usuario_id !== Number(req.usuario.sub)) return res.status(403).json({ erro: 'Você só pode remover seu comentário.' }); await executar('DELETE FROM comentarios WHERE id=?', [comentario.id]); return res.status(204).end(); } catch (e) { return next(e); } }
module.exports = { listarComentarios, criarComentario, criarComentarioExercicio, curtirComentario, removerComentario };
