const { executar, buscar, listar } = require('../config/conexaoBanco');
const { textoObrigatorio } = require('../utilitarios/validadores');
const { registrarAcao } = require('../servicos/medalhasServico');

async function seguirUsuario(req,res,next){try{const alvo=await buscar('SELECT id,nome_completo FROM usuarios WHERE id=? AND ativo=1',[req.params.id]);if(!alvo)return res.status(404).json({erro:'Usuário não encontrado.'});if(Number(req.usuario.sub)===alvo.id)return res.status(422).json({erro:'Você não pode seguir a si mesmo.'});const existe=await buscar('SELECT 1 FROM usuarios_seguem_usuarios WHERE seguidor_id=? AND seguindo_id=?',[req.usuario.sub,alvo.id]);if(existe){await executar('DELETE FROM usuarios_seguem_usuarios WHERE seguidor_id=? AND seguindo_id=?',[req.usuario.sub,alvo.id]);return res.json({seguindo:false});}await executar('INSERT INTO usuarios_seguem_usuarios (seguidor_id,seguindo_id) VALUES (?,?)',[req.usuario.sub,alvo.id]);await registrarAcao(req.usuario.sub,'seguiu',alvo.id,15);await executar('INSERT INTO notificacoes (usuario_id,tipo,titulo,conteudo) VALUES (?,?,?,?)',[alvo.id,'novo_seguidor','Novo seguidor','Alguém começou a seguir seu perfil.']);return res.json({seguindo:true});}catch(e){return next(e);}}
async function bloquear(req,res,next){try{if(Number(req.usuario.sub)===Number(req.params.id))return res.status(422).json({erro:'Você não pode bloquear a si mesmo.'});await executar('INSERT OR REPLACE INTO bloqueios (bloqueador_id,bloqueado_id,motivo) VALUES (?,?,?)',[req.usuario.sub,req.params.id,req.body.motivo||null]);return res.status(201).json({bloqueado:true});}catch(e){return next(e);}}
async function registrarPeso(req,res,next){try{const peso=Number(req.body.peso);if(!Number.isFinite(peso)||peso<=0)return res.status(422).json({erro:'Informe um peso válido.'});const resultado=await executar('INSERT INTO historico_peso (usuario_id,peso,anotacao) VALUES (?,?,?)',[req.usuario.sub,peso,req.body.anotacao||null]);await executar('UPDATE usuarios SET peso_atual=?,data_atualizacao=CURRENT_TIMESTAMP WHERE id=?',[peso,req.usuario.sub]);await registrarAcao(req.usuario.sub,'peso_registrado',resultado.id,10);return res.status(201).json({peso});}catch(e){return next(e);}}
async function historicoPeso(req,res,next){try{return res.json(await listar('SELECT peso,anotacao,data_registro FROM historico_peso WHERE usuario_id=? ORDER BY data_registro',[req.usuario.sub]));}catch(e){return next(e);}}
async function seguirPlano(req,res,next){try{const plano=await buscar('SELECT id FROM planos_alimentares WHERE id=? AND ativo=1',[req.params.id]);if(!plano)return res.status(404).json({erro:'Plano não encontrado.'});const existe=await buscar('SELECT 1 FROM usuarios_seguem_planos WHERE usuario_id=? AND plano_id=?',[req.usuario.sub,plano.id]);if(existe){await executar('DELETE FROM usuarios_seguem_planos WHERE usuario_id=? AND plano_id=?',[req.usuario.sub,plano.id]);await executar('UPDATE planos_alimentares SET seguidores=MAX(seguidores-1,0) WHERE id=?',[plano.id]);return res.json({seguindo:false});}await executar('INSERT INTO usuarios_seguem_planos (usuario_id,plano_id) VALUES (?,?)',[req.usuario.sub,plano.id]);await executar('UPDATE planos_alimentares SET seguidores=seguidores+1 WHERE id=?',[plano.id]);return res.status(201).json({seguindo:true});}catch(e){return next(e);}}
async function progressoPlano(req,res,next){try{const dias=Math.max(Number(req.body.dias_completos)||0,0);await executar('UPDATE usuarios_seguem_planos SET dias_completos=?,saiu_da_dieta=? WHERE usuario_id=? AND plano_id=?',[dias,req.body.saiu_da_dieta?1:0,req.usuario.sub,req.params.id]);return res.json({dias_completos:dias});}catch(e){return next(e);}}
async function notificacoes(req,res,next){try{return res.json(await listar('SELECT * FROM notificacoes WHERE usuario_id=? ORDER BY data_criacao DESC LIMIT 50',[req.usuario.sub]));}catch(e){return next(e);}}
async function lerNotificacao(req,res,next){try{await executar('UPDATE notificacoes SET lido=1 WHERE id=? AND usuario_id=?',[req.params.id,req.usuario.sub]);return res.status(204).end();}catch(e){return next(e);}}
async function denunciar(req,res,next){try{if(!textoObrigatorio(req.body.tipo)||!Number(req.body.alvo_id)||!textoObrigatorio(req.body.motivo))return res.status(422).json({erro:'Tipo, alvo e motivo são obrigatórios.'});const r=await executar('INSERT INTO reportes (denunciante_id,tipo,alvo_id,motivo) VALUES (?,?,?,?)',[req.usuario.sub,req.body.tipo,req.body.alvo_id,req.body.motivo.trim()]);return res.status(201).json({id:r.id});}catch(e){return next(e);}}
module.exports={seguirUsuario,bloquear,registrarPeso,historicoPeso,seguirPlano,progressoPlano,notificacoes,lerNotificacao,denunciar};
