const { executar, buscar, listar } = require('../config/conexaoBanco');
const { textoObrigatorio } = require('../utilitarios/validadores');
const { urlDoArquivo } = require('../servicos/uploadServico');
const { registrarAcao } = require('../servicos/medalhasServico');

const donoOuAdmin = (item, usuario, res) => {
  if (!item) { res.status(404).json({ erro: 'Conteúdo não encontrado.' }); return false; }
  if (item.criado_por !== Number(usuario.sub) && usuario.role !== 'admin') { res.status(403).json({ erro: 'Você só pode alterar seu próprio conteúdo.' }); return false; }
  return true;
};
const json = (valor) => Array.isArray(valor) ? JSON.stringify(valor) : (valor || '[]');

async function criarReceita(req, res, next) {
  try {
    const d = req.body;
    if (![d.titulo, d.descricao, d.modo_preparo].every(textoObrigatorio)) return res.status(422).json({ erro: 'Título, descrição e modo de preparo são obrigatórios.' });
    const r = await executar(`INSERT INTO receitas (titulo, descricao, modo_preparo, criado_por, calorias, proteina, carboidrato, gordura, fibra, foto_url, tempo_preparo, porcoes, dificuldade, categoria, alergenicos, dietas) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`, [d.titulo.trim(), d.descricao.trim(), d.modo_preparo.trim(), req.usuario.sub, d.calorias || null, d.proteina || null, d.carboidrato || null, d.gordura || null, d.fibra || null, urlDoArquivo(req) || d.foto_url || null, d.tempo_preparo || null, d.porcoes || null, d.dificuldade || null, d.categoria || null, json(d.alergenicos), json(d.dietas)]);
    return res.status(201).json(await detalheReceita(r.id));
  } catch (erro) { return next(erro); }
}
async function detalheReceita(id) {
  return buscar(`SELECT r.*, u.nome_completo AS autor_nome, u.foto_perfil_url AS autor_foto, u.role AS autor_role, COUNT(c.id) AS comentarios FROM receitas r JOIN usuarios u ON u.id = r.criado_por LEFT JOIN comentarios c ON c.receita_id = r.id WHERE r.id = ? AND r.ativo = 1 GROUP BY r.id`, [id]);
}
async function obterReceita(req, res, next) { try { const receita = await detalheReceita(req.params.id); return receita ? res.json(receita) : res.status(404).json({ erro: 'Receita não encontrada.' }); } catch (e) { return next(e); } }
async function listarReceitas(req, res, next) { try { const pagina = Math.max(Number(req.query.page) || 1, 1); const limite = Math.min(Math.max(Number(req.query.limit) || 10, 1), 50); const parametros = []; let filtro = 'WHERE r.ativo = 1'; if (req.query.categoria) { filtro += ' AND r.categoria = ?'; parametros.push(req.query.categoria); } const total = await buscar(`SELECT COUNT(*) AS total FROM receitas r ${filtro}`, parametros); const itens = await listar(`SELECT r.*, u.nome_completo AS autor_nome, u.foto_perfil_url AS autor_foto FROM receitas r JOIN usuarios u ON u.id = r.criado_por ${filtro} ORDER BY r.data_criacao DESC LIMIT ? OFFSET ?`, [...parametros, limite, (pagina - 1) * limite]); return res.json({ pagina, limite, total: total.total, itens }); } catch (e) { return next(e); } }
async function atualizarReceita(req, res, next) {
  try { const receita = await buscar('SELECT * FROM receitas WHERE id = ?', [req.params.id]); if (!donoOuAdmin(receita, req.usuario, res)) return;
    const permitidos = ['titulo', 'descricao', 'modo_preparo', 'calorias', 'proteina', 'carboidrato', 'gordura', 'fibra', 'foto_url', 'tempo_preparo', 'porcoes', 'dificuldade', 'categoria'];
    const campos = permitidos.filter((campo) => req.body[campo] !== undefined); if (!campos.length) return res.status(422).json({ erro: 'Nenhum campo válido para atualizar.' });
    await executar(`UPDATE receitas SET ${campos.map((c) => `${c} = ?`).join(', ')} WHERE id = ?`, [...campos.map((c) => req.body[c]), receita.id]); return res.json(await detalheReceita(receita.id));
  } catch (e) { return next(e); }
}
async function removerReceita(req, res, next) { try { const receita = await buscar('SELECT * FROM receitas WHERE id = ?', [req.params.id]); if (!donoOuAdmin(receita, req.usuario, res)) return; await executar('UPDATE receitas SET ativo = 0 WHERE id = ?', [receita.id]); return res.status(204).end(); } catch (e) { return next(e); } }
async function curtirReceita(req, res, next) { try { const receita = await buscar('SELECT id FROM receitas WHERE id = ? AND ativo = 1', [req.params.id]); if (!receita) return res.status(404).json({ erro: 'Receita não encontrada.' }); const jaCurtiu = await buscar('SELECT 1 FROM curtidas_receitas WHERE usuario_id = ? AND receita_id = ?', [req.usuario.sub, receita.id]); if (jaCurtiu) { await executar('DELETE FROM curtidas_receitas WHERE usuario_id = ? AND receita_id = ?', [req.usuario.sub, receita.id]); await executar('UPDATE receitas SET curtidas = MAX(curtidas - 1, 0) WHERE id = ?', [receita.id]); return res.json({ curtido: false }); } await executar('INSERT INTO curtidas_receitas (usuario_id, receita_id) VALUES (?, ?)', [req.usuario.sub, receita.id]); await executar('UPDATE receitas SET curtidas = curtidas + 1 WHERE id = ?', [receita.id]); await registrarAcao(req.usuario.sub, 'curtida', `receita:${receita.id}`, 2); return res.json({ curtido: true }); } catch (e) { return next(e); } }
async function descurtirReceita(req, res, next) { try { const receita = await buscar('SELECT id FROM receitas WHERE id = ? AND ativo = 1', [req.params.id]); if (!receita) return res.status(404).json({ erro: 'Receita não encontrada.' }); await executar('DELETE FROM curtidas_receitas WHERE usuario_id = ? AND receita_id = ?', [req.usuario.sub, receita.id]); await executar('UPDATE receitas SET curtidas = MAX(curtidas - 1, 0) WHERE id = ? AND curtidas > 0', [receita.id]); return res.json({ curtido: false }); } catch (e) { return next(e); } }
async function criarExercicio(req, res, next) { try { const d = req.body; if (![d.nome, d.descricao, d.tecnica].every(textoObrigatorio)) return res.status(422).json({ erro: 'Nome, descrição e técnica são obrigatórios.' }); const r = await executar(`INSERT INTO exercicios (nome, descricao, tecnica, criado_por, video_url, musculos_trabalhados, dificuldade, series_recomendadas, repeticoes_recomendadas, descanso_segundos, contraindicacoes) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`, [d.nome.trim(), d.descricao.trim(), d.tecnica.trim(), req.usuario.sub, urlDoArquivo(req) || d.video_url || null, json(d.musculos_trabalhados), d.dificuldade || null, d.series_recomendadas || null, d.repeticoes_recomendadas || null, d.descanso_segundos || null, d.contraindicacoes || null]); return res.status(201).json(await buscar('SELECT * FROM exercicios WHERE id = ?', [r.id])); } catch (e) { return next(e); } }
async function listarExercicios(req, res, next) { try { const parametros = []; let filtro = 'WHERE e.ativo = 1'; if (req.query.musculo) { filtro += ' AND e.musculos_trabalhados LIKE ?'; parametros.push(`%${req.query.musculo}%`); } return res.json(await listar(`SELECT e.*, u.nome_completo AS autor_nome FROM exercicios e JOIN usuarios u ON u.id = e.criado_por ${filtro} ORDER BY e.data_criacao DESC LIMIT 50`, parametros)); } catch (e) { return next(e); } }
async function obterExercicio(req, res, next) { try { const item = await buscar('SELECT e.*, u.nome_completo AS autor_nome FROM exercicios e JOIN usuarios u ON u.id = e.criado_por WHERE e.id = ? AND e.ativo = 1', [req.params.id]); return item ? res.json(item) : res.status(404).json({ erro: 'Exercício não encontrado.' }); } catch (e) { return next(e); } }
async function alterarExercicio(req, res, next) { try { const item = await buscar('SELECT * FROM exercicios WHERE id = ?', [req.params.id]); if (!donoOuAdmin(item, req.usuario, res)) return; const permitidos = ['nome', 'descricao', 'tecnica', 'video_url', 'musculos_trabalhados', 'dificuldade', 'series_recomendadas', 'repeticoes_recomendadas', 'descanso_segundos', 'contraindicacoes']; const campos = permitidos.filter((campo) => req.body[campo] !== undefined); if (!campos.length) return res.status(422).json({ erro: 'Nenhum campo válido para atualizar.' }); await executar(`UPDATE exercicios SET ${campos.map((c) => `${c} = ?`).join(', ')} WHERE id = ?`, [...campos.map((c) => c === 'musculos_trabalhados' ? json(req.body[c]) : req.body[c]), item.id]); return obterExercicio({ params: { id: item.id } }, res, next); } catch (e) { return next(e); } }
async function removerExercicio(req, res, next) { try { const item = await buscar('SELECT * FROM exercicios WHERE id = ?', [req.params.id]); if (!donoOuAdmin(item, req.usuario, res)) return; await executar('UPDATE exercicios SET ativo = 0 WHERE id = ?', [item.id]); return res.status(204).end(); } catch (e) { return next(e); } }
async function curtirExercicio(req, res, next) { try { const item = await buscar('SELECT id FROM exercicios WHERE id = ? AND ativo = 1', [req.params.id]); if (!item) return res.status(404).json({ erro: 'Exercício não encontrado.' }); const curtida = await buscar('SELECT 1 FROM curtidas_exercicios WHERE usuario_id = ? AND exercicio_id = ?', [req.usuario.sub, item.id]); if (curtida) { await executar('DELETE FROM curtidas_exercicios WHERE usuario_id = ? AND exercicio_id = ?', [req.usuario.sub, item.id]); await executar('UPDATE exercicios SET curtidas = MAX(curtidas - 1, 0) WHERE id = ?', [item.id]); return res.json({ curtido: false }); } await executar('INSERT INTO curtidas_exercicios VALUES (?, ?)', [req.usuario.sub, item.id]); await executar('UPDATE exercicios SET curtidas = curtidas + 1 WHERE id = ?', [item.id]); await registrarAcao(req.usuario.sub, 'curtida', `exercicio:${item.id}`, 2); return res.json({ curtido: true }); } catch (e) { return next(e); } }
async function descurtirExercicio(req, res, next) { try { const item = await buscar('SELECT id FROM exercicios WHERE id = ? AND ativo = 1', [req.params.id]); if (!item) return res.status(404).json({ erro: 'Exercício não encontrado.' }); await executar('DELETE FROM curtidas_exercicios WHERE usuario_id = ? AND exercicio_id = ?', [req.usuario.sub, item.id]); await executar('UPDATE exercicios SET curtidas = MAX(curtidas - 1, 0) WHERE id = ? AND curtidas > 0', [item.id]); return res.json({ curtido: false }); } catch (e) { return next(e); } }
module.exports = { criarReceita, listarReceitas, obterReceita, atualizarReceita, removerReceita, curtirReceita, descurtirReceita, criarExercicio, listarExercicios, obterExercicio, alterarExercicio, removerExercicio, curtirExercicio, descurtirExercicio };
