const { executar,buscar,listar }=require('../config/conexaoBanco'); const { textoObrigatorio }=require('../utilitarios/validadores');
async function enviar(req,res,next){try{const {destinatario_id,conteudo,tipo='texto'}=req.body;if(!Number(destinatario_id)||!textoObrigatorio(conteudo))return res.status(422).json({erro:'Destinatário e mensagem são obrigatórios.'});const destinatario=await buscar('SELECT id FROM usuarios WHERE id=? AND ativo=1',[destinatario_id]);if(!destinatario)return res.status(404).json({erro:'Destinatário não encontrado.'});const r=await executar('INSERT INTO mensagens (remetente_id,destinatario_id,conteudo,tipo) VALUES (?,?,?,?)',[req.usuario.sub,destinatario_id,conteudo.trim(),tipo]);await executar('INSERT INTO notificacoes (usuario_id,tipo,titulo,conteudo,relacionado_id) VALUES (?,?,?,?,?)',[destinatario_id,'mensagem','Nova mensagem',conteudo.trim().slice(0,100),r.id]);return res.status(201).json(await buscar('SELECT * FROM mensagens WHERE id=?',[r.id]));}catch(e){return next(e);}}
async function conversa(req,res,next){try{const outro=Number(req.params.usuarioId);await executar('UPDATE mensagens SET lido=1 WHERE remetente_id=? AND destinatario_id=?',[outro,req.usuario.sub]);return res.json(await listar('SELECT m.*,u.nome_completo remetente_nome FROM mensagens m JOIN usuarios u ON u.id=m.remetente_id WHERE (m.remetente_id=? AND m.destinatario_id=?) OR (m.remetente_id=? AND m.destinatario_id=?) ORDER BY m.data_criacao',[req.usuario.sub,outro,outro,req.usuario.sub]));}catch(e){return next(e);}}
async function conversas(req,res,next){try{return res.json(await listar(`SELECT u.id,u.nome_completo,u.foto_perfil_url,MAX(m.data_criacao) ultima_mensagem,SUM(CASE WHEN m.destinatario_id=? AND m.lido=0 THEN 1 ELSE 0 END) nao_lidas FROM mensagens m JOIN usuarios u ON u.id=CASE WHEN m.remetente_id=? THEN m.destinatario_id ELSE m.remetente_id END WHERE m.remetente_id=? OR m.destinatario_id=? GROUP BY u.id ORDER BY ultima_mensagem DESC`,[req.usuario.sub,req.usuario.sub,req.usuario.sub,req.usuario.sub]));}catch(e){return next(e);}}
async function criarGrupo(req,res,next){try{if(!textoObrigatorio(req.body.nome)||!textoObrigatorio(req.body.descricao))return res.status(422).json({erro:'Nome e descrição são obrigatórios.'});const r=await executar('INSERT INTO grupos_suporte (nome,descricao,criado_por) VALUES (?,?,?)',[req.body.nome.trim(),req.body.descricao.trim(),req.usuario.sub]);await executar("INSERT INTO membros_grupo (grupo_id,usuario_id,papel) VALUES (?,?,'admin')",[r.id,req.usuario.sub]);return res.status(201).json({id:r.id,nome:req.body.nome});}catch(e){return next(e);}}
async function entrarGrupo(req,res,next){try{await executar("INSERT OR IGNORE INTO membros_grupo (grupo_id,usuario_id,papel) VALUES (?,?,'membro')",[req.params.id,req.usuario.sub]);return res.status(201).json({membro:true});}catch(e){return next(e);}}
async function mensagensGrupo(req,res,next){try{const membro=await buscar('SELECT 1 FROM membros_grupo WHERE grupo_id=? AND usuario_id=?',[req.params.id,req.usuario.sub]);if(!membro)return res.status(403).json({erro:'Entre no grupo para acessar as mensagens.'});return res.json(await listar('SELECT mg.*,u.nome_completo,u.foto_perfil_url FROM mensagens_grupo mg JOIN usuarios u ON u.id=mg.usuario_id WHERE grupo_id=? ORDER BY data_criacao',[req.params.id]));}catch(e){return next(e);}}
async function enviarGrupo(req,res,next){try{if(!textoObrigatorio(req.body.conteudo))return res.status(422).json({erro:'A mensagem não pode estar vazia.'});const membro=await buscar('SELECT 1 FROM membros_grupo WHERE grupo_id=? AND usuario_id=?',[req.params.id,req.usuario.sub]);if(!membro)return res.status(403).json({erro:'Entre no grupo antes de enviar mensagens.'});const r=await executar('INSERT INTO mensagens_grupo (grupo_id,usuario_id,conteudo) VALUES (?,?,?)',[req.params.id,req.usuario.sub,req.body.conteudo.trim()]);return res.status(201).json(await buscar('SELECT * FROM mensagens_grupo WHERE id=?',[r.id]));}catch(e){return next(e);}}
module.exports={enviar,conversa,conversas,criarGrupo,entrarGrupo,mensagensGrupo,enviarGrupo};
