const { executar, buscar, listar } = require('../config/conexaoBanco');
const { textoObrigatorio } = require('../utilitarios/validadores');
const donoOuAdmin = (item, usuario, res) => { if (!item) { res.status(404).json({ erro: 'Plano não encontrado.' }); return false; } if (item.criado_por !== Number(usuario.sub) && usuario.role !== 'admin') { res.status(403).json({ erro: 'Você só pode alterar seu próprio plano.' }); return false; } return true; };
async function detalhe(id) { const plano = await buscar('SELECT p.*, u.nome_completo AS autor_nome FROM planos_alimentares p JOIN usuarios u ON u.id=p.criado_por WHERE p.id=? AND p.ativo=1', [id]); if (!plano) return null; plano.receitas = await listar('SELECT pr.*, r.titulo, r.foto_url FROM planos_receitas pr JOIN receitas r ON r.id=pr.receita_id WHERE pr.plano_id=? ORDER BY pr.dia_plano, pr.id', [id]); plano.exercicios = await listar('SELECT pe.*, e.nome, e.video_url FROM planos_exercicios pe JOIN exercicios e ON e.id=pe.exercicio_id WHERE pe.plano_id=? ORDER BY pe.dia_semana, pe.ordem, pe.id', [id]); return plano; }
async function listarPlanos(req, res, next) { try { const filtro = req.query.tipo ? 'AND p.tipo=?' : ''; const parametros = req.query.tipo ? [req.query.tipo] : []; return res.json(await listar(`SELECT p.*, u.nome_completo AS autor_nome FROM planos_alimentares p JOIN usuarios u ON u.id=p.criado_por WHERE p.ativo=1 ${filtro} ORDER BY p.data_criacao DESC LIMIT 50`, parametros)); } catch (e) { return next(e); } }
async function criarPlano(req, res, next) { try { const d=req.body; if (!textoObrigatorio(d.titulo)||!textoObrigatorio(d.descricao)) return res.status(422).json({ erro:'Título e descrição são obrigatórios.' }); const r=await executar('INSERT INTO planos_alimentares (titulo,descricao,criado_por,duracao_dias,calorias_alvo,dificuldade,tipo,proteina_alvo,carboidrato_alvo,gordura_alvo,data_inicio,data_fim,foto_capa_url) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)',[d.titulo.trim(),d.descricao.trim(),req.usuario.sub,d.duracao_dias||null,d.calorias_alvo||null,d.dificuldade||null,d.tipo||'público',d.proteina_alvo||null,d.carboidrato_alvo||null,d.gordura_alvo||null,d.data_inicio||null,d.data_fim||null,d.foto_capa_url||null]); for (const item of (Array.isArray(d.receitas)?d.receitas:[])) await executar('INSERT INTO planos_receitas (plano_id,receita_id,dia_plano,refeicao) VALUES (?,?,?,?)',[r.id,item.receita_id,item.dia||item.dia_plano||null,item.refeicao||null]); for (const item of (Array.isArray(d.exercicios)?d.exercicios:[])) await executar('INSERT INTO planos_exercicios (plano_id,exercicio_id,dia_semana,ordem,series_personalizado,repeticoes_personalizado) VALUES (?,?,?,?,?,?)',[r.id,item.exercicio_id,item.dia_semana||null,item.ordem||null,item.series_personalizado||null,item.repeticoes_personalizado||null]); return res.status(201).json(await detalhe(r.id)); } catch(e) { return next(e); } }
async function obterPlano(req,res,next){try{const p=await detalhe(req.params.id);return p?res.json(p):res.status(404).json({erro:'Plano não encontrado.'});}catch(e){return next(e);}}
async function atualizarPlano(req,res,next){try{const p=await buscar('SELECT * FROM planos_alimentares WHERE id=?',[req.params.id]);if(!donoOuAdmin(p,req.usuario,res))return;const permitidos=['titulo','descricao','duracao_dias','calorias_alvo','dificuldade','tipo','proteina_alvo','carboidrato_alvo','gordura_alvo','data_inicio','data_fim','foto_capa_url'];const campos=permitidos.filter(c=>req.body[c]!==undefined);if(!campos.length)return res.status(422).json({erro:'Nenhum campo válido para atualizar.'});await executar(`UPDATE planos_alimentares SET ${campos.map(c=>`${c}=?`).join(',')} WHERE id=?`,[...campos.map(c=>req.body[c]),p.id]);return obterPlano({params:{id:p.id}},res,next);}catch(e){return next(e);}}
async function removerPlano(req,res,next){try{const p=await buscar('SELECT * FROM planos_alimentares WHERE id=?',[req.params.id]);if(!donoOuAdmin(p,req.usuario,res))return;await executar('UPDATE planos_alimentares SET ativo=0 WHERE id=?',[p.id]);return res.status(204).end();}catch(e){return next(e);}}
async function adicionarReceita(req,res,next){try{const p=await buscar('SELECT * FROM planos_alimentares WHERE id=? AND ativo=1',[req.params.id]);if(!p)return res.status(404).json({erro:'Plano não encontrado.'});await executar('INSERT INTO planos_receitas (plano_id,receita_id,dia_plano,refeicao) VALUES (?,?,?,?)',[p.id,req.body.receita_id,req.body.dia||null,req.body.refeicao||null]);return res.status(201).json(await detalhe(p.id));}catch(e){return next(e);}}
async function removerReceita(req,res,next){try{await executar('DELETE FROM planos_receitas WHERE plano_id=? AND receita_id=?',[req.params.id,req.params.receitaId]);return res.status(204).end();}catch(e){return next(e);}}
async function adicionarExercicio(req,res,next){try{const p=await buscar('SELECT * FROM planos_alimentares WHERE id=? AND ativo=1',[req.params.id]);if(!p)return res.status(404).json({erro:'Plano não encontrado.'});await executar('INSERT INTO planos_exercicios (plano_id,exercicio_id,dia_semana,ordem,series_personalizado,repeticoes_personalizado) VALUES (?,?,?,?,?,?)',[p.id,req.body.exercicio_id,req.body.dia_semana||null,req.body.ordem||null,req.body.series_personalizado||null,req.body.repeticoes_personalizado||null]);return res.status(201).json(await detalhe(p.id));}catch(e){return next(e);}}
module.exports={listarPlanos,criarPlano,obterPlano,atualizarPlano,removerPlano,adicionarReceita,removerReceita,adicionarExercicio};
