export const receitasDemo = [
  { id: 91001, titulo: 'Aveia cremosa com iogurte, chia e frutas', categoria: 'café da manhã', descricao: 'Aveia, fruta e sementes para um café da manhã simples e nutritivo. Nutrientes estimados por porção.', modo_preparo: 'Misture 40 g de aveia, 150 g de iogurte natural e 10 g de chia. Deixe na geladeira por pelo menos 4 horas. Sirva com morangos e banana fatiada.', calorias: 365, proteina: 20, carboidrato: 54, gordura: 8, fibra: 10, tempo_preparo: 10, porcoes: 1, alergenicos: ['leite'], dietas: ['vegetariana'], foto_url: null, curtidas: 18, autor_nome: 'Equipe Aptus' },
  { id: 91002, titulo: 'Bowl brasileiro de frango, arroz integral e feijão', categoria: 'almoço', descricao: 'Uma combinação caseira com cereal, leguminosa, frango e abóbora. Nutrientes estimados por porção.', modo_preparo: 'Cozinhe arroz integral e feijão. Tempere o frango com alho e limão e grelhe até cozinhar completamente. Asse ou cozinhe a abóbora em cubos. Sirva tudo junto com cheiro-verde.', calorias: 535, proteina: 43, carboidrato: 68, gordura: 10, fibra: 13, tempo_preparo: 35, porcoes: 1, alergenicos: [], dietas: [], foto_url: null, curtidas: 26, autor_nome: 'Equipe Aptus' },
  { id: 91003, titulo: 'Salada morna de lentilha com tomate e pepino', categoria: 'almoço', descricao: 'Lentilhas, vegetais frescos e molho de limão com azeite. Nutrientes estimados por porção.', modo_preparo: 'Cozinhe 180 g de lentilhas até ficarem macias e escorra. Misture com tomate, pepino, cebola roxa e salsinha picados. Tempere com limão, azeite, pimenta e sal a gosto.', calorias: 345, proteina: 17, carboidrato: 52, gordura: 8, fibra: 16, tempo_preparo: 25, porcoes: 1, alergenicos: [], dietas: ['vegetariana', 'vegana'], foto_url: null, curtidas: 21, autor_nome: 'Equipe Aptus' },
  { id: 91004, titulo: 'Peixe assado com batata e brócolis', categoria: 'jantar', descricao: 'Filé de peixe assado servido com batata e brócolis. Nutrientes estimados por porção.', modo_preparo: 'Aqueça o forno a 200 °C. Asse batatas em cubos por 15 minutos. Tempere o peixe com limão e alho e asse por mais 12 a 15 minutos, até ficar opaco e se desfazer facilmente. Cozinhe o brócolis no vapor e sirva junto.', calorias: 410, proteina: 36, carboidrato: 48, gordura: 9, fibra: 8, tempo_preparo: 35, porcoes: 1, alergenicos: ['peixe'], dietas: [], foto_url: null, curtidas: 15, autor_nome: 'Equipe Aptus' },
  { id: 91005, titulo: 'Omelete de espinafre e tomate com pão integral', categoria: 'café da manhã', descricao: 'Ovos com vegetais frescos, acompanhados de pão integral. Nutrientes estimados por porção.', modo_preparo: 'Bata 2 ovos com pimenta e uma pitada de sal. Refogue tomate e espinafre em uma frigideira antiaderente. Adicione os ovos e cozinhe em fogo baixo até firmar. Sirva com uma fatia de pão integral.', calorias: 350, proteina: 24, carboidrato: 31, gordura: 14, fibra: 6, tempo_preparo: 15, porcoes: 1, alergenicos: ['ovo', 'glúten'], dietas: ['vegetariana'], foto_url: null, curtidas: 19, autor_nome: 'Equipe Aptus' },
  { id: 91006, titulo: 'Grão-de-bico com legumes e molho de tahine', categoria: 'jantar', descricao: 'Prato vegetal com grão-de-bico e legumes assados. Nutrientes estimados por porção.', modo_preparo: 'Aqueça o forno a 210 °C. Misture grão-de-bico cozido, cenoura e abobrinha em cubos com azeite, cominho e páprica; asse por 18 a 20 minutos. Misture tahine, limão e água para o molho e sirva por cima.', calorias: 435, proteina: 17, carboidrato: 58, gordura: 16, fibra: 15, tempo_preparo: 25, porcoes: 1, alergenicos: ['gergelim'], dietas: ['vegetariana', 'vegana'], foto_url: null, curtidas: 23, autor_nome: 'Equipe Aptus' },
];

export const exerciciosDemo = [
  { id: 92001, nome: 'Agachamento livre', descricao: 'Fortalece pernas e glúteos usando o peso do corpo.', tecnica: 'Mantenha o peito aberto, leve o quadril para trás e alinhe os joelhos aos pés.', musculos_trabalhados: ['perna', 'glúteo'], ambientes: '["casa","academia"]', dificuldade: 2, series_recomendadas: 3, repeticoes_recomendadas: 12 },
  { id: 92002, nome: 'Flexão de braços adaptada', descricao: 'Exercício para peito e braços; pode ser executado com os joelhos apoiados.', tecnica: 'Apoie as mãos abaixo dos ombros, mantenha o corpo alinhado e desça com controle.', musculos_trabalhados: ['peito', 'braço', 'ombro'], ambientes: '["casa","academia"]', dificuldade: 2, series_recomendadas: 3, repeticoes_recomendadas: 10 },
  { id: 92003, nome: 'Ponte de glúteos', descricao: 'Movimento no solo para glúteos e região posterior das pernas.', tecnica: 'Deite com os joelhos flexionados, apoie os pés e eleve o quadril sem arquear a lombar.', musculos_trabalhados: ['glúteo', 'perna'], ambientes: '["casa"]', dificuldade: 1, series_recomendadas: 3, repeticoes_recomendadas: 12 },
];
